package mx.tesivil.detector;

import org.junit.Test;
import java.time.LocalDate;
import java.util.List;
import static org.junit.Assert.*;

public class DecisionInsightsTest {
    private DriverConfig c(){DriverConfig c=new DriverConfig();c.calibrated=c.vehicleConfirmed=c.energyReviewed=c.costsReviewed=c.goalsReviewed=true;c.zoneFilter=c.riderFilter=false;c.minHourly=20;c.targetHourly=40;c.minPerKm=1;c.targetPerKm=2;return c;}
    private OfferParser.Offer offer(long cents){return new OfferParser.Offer(cents,11,6.7,5,1.3,null,"Calle Uno, Zapopan","Calle Dos, Guadalajara");}
    private ScoreEngine.Evaluation e(DriverConfig c,long cents){return ScoreEngine.evaluate(offer(cents),c,List.of(),LocalDate.of(2026,9,13),12);}
    @Test public void disproportionatePickupUsesVisibleTotalsAndDoesNotPenalizeTwice(){DriverConfig c=c();c.passengerWaitMin=30;c.repositionMin=40;c.repositionKm=10;ScoreEngine.Evaluation a=e(c,100000);assertEquals(83.75,a.pickupKmShare,1e-6);assertEquals(68.75,a.pickupTimeShare,1e-6);assertTrue(a.pickupDisproportionate);c.pickupShareAlertPercent=100;ScoreEngine.Evaluation b=e(c,100000);assertFalse(b.pickupDisproportionate);assertEquals(a.economyScore,b.economyScore);assertEquals(a.score,b.score);}
    @Test public void inverseWaitFailsAtTheFirstHourlyOrKmFloor(){DriverConfig c=c();c.minHourly=120;c.targetHourly=180;ScoreEngine.Evaluation a=e(c,20000);assertTrue(a.extraWaitToleranceMin>0);c.passengerWaitMin+=a.extraWaitToleranceMin-.00001;ScoreEngine.Evaluation before=e(c,20000);assertFalse(before.belowFloor);c.passengerWaitMin+=.00002;assertTrue(e(c,20000).belowFloor);}
    @Test public void inverseWaitHonorsKmFloorWhenFixedCostDominates(){DriverConfig c=c();c.minHourly=.01;c.targetHourly=1;c.minPerKm=18;c.targetPerKm=20;ScoreEngine.Evaluation a=e(c,20000);assertTrue(a.extraWaitToleranceMin>0);c.passengerWaitMin+=a.extraWaitToleranceMin+.0001;ScoreEngine.Evaluation b=e(c,20000);assertTrue(b.perKm<c.minPerKm);assertTrue(b.hourly>c.minHourly);}
    @Test public void noFixedCostsDoesNotHideAnAlreadyBrokenKmFloor(){DriverConfig c=c();c.fixedMonthly=0;c.minPerKm=30;c.targetPerKm=40;ScoreEngine.Evaluation a=e(c,20000);assertTrue(a.belowFloor);assertEquals(0,a.extraWaitToleranceMin,0);}
    @Test public void minimumFareIncludesFeesAndRoundsUpToCents(){DriverConfig c=c();c.additionalFeePercent=17;c.minHourly=120;c.targetHourly=180;c.minPerKm=5;c.targetPerKm=8;ScoreEngine.Evaluation a=e(c,20000);long floor=Math.round(a.minimumFare*100);assertFalse(e(c,floor).belowFloor);assertTrue(e(c,floor-1).belowFloor);}
    @Test public void economicFareCannotOverridePersonalRiderBlock(){DriverConfig c=c();c.riderFilter=true;OfferParser.Offer o=new OfferParser.Offer(100000,1,1,10,5,null,"A","B",new RiderProfile(5d,4,false,false,"TEST"));ScoreEngine.Evaluation a=ScoreEngine.evaluate(o,c,List.of(),LocalDate.now(),12);assertFalse(a.belowFloor);assertTrue(a.riderBlocked);assertEquals(ScoreEngine.Color.ROJO,a.color);}
    @Test public void returnAlternativeReplacesRatherThanAddsBaseRepositioning(){DriverConfig c=c();c.repositionKm=30;c.repositionMin=40;c.returnScenarioEnabled=true;c.returnScenarioKm=10;c.returnScenarioMin=20;ScoreEngine.Evaluation a=e(c,50000);assertEquals(38,a.km,0);assertEquals(18,a.returnKm,0);assertEquals(39,a.returnMinutes,0);DriverConfig alternative=c();alternative.repositionKm=10;alternative.repositionMin=20;ScoreEngine.Evaluation b=e(alternative,50000);assertEquals(b.margin,a.returnMargin,1e-6);assertEquals(b.hourly,a.returnHourly,1e-6);}
    @Test public void phevReturnConsumesRemainingElectricRangeOnce(){DriverConfig c=c();c.energyMode="PHEV";c.remainingElectricKm=5;c.electricityPrice=2;c.rangeUpdatedAtMs=System.currentTimeMillis();c.returnScenarioEnabled=true;c.returnScenarioKm=10;c.returnScenarioMin=20;ScoreEngine.Evaluation a=e(c,50000);double energy=5*.2*2+13d/12*25;double upkeep=18*1.5;double fixed=39d/60*18.75;assertEquals(500-energy-upkeep-fixed,a.returnMargin,1e-6);}
    @Test public void returnScenarioCannotImproveAnyRed(){DriverConfig c=c();c.maxPickupKm=1;c.returnScenarioEnabled=true;c.returnScenarioKm=300;c.returnScenarioMin=300;ScoreEngine.Evaluation a=e(c,8000);assertTrue(a.returnBelowFloor);assertEquals(ScoreEngine.Color.ROJO,a.color);}
    @Test public void missingReviewCategoriesBlockGreenEvenAfterOldGeneralAcknowledgement(){DriverConfig c=c();c.costsReviewed=false;ScoreEngine.Evaluation a=e(c,100000);assertTrue(a.profilePending);assertEquals(ScoreEngine.Color.AMBAR,a.color);assertTrue(a.pending.toString().contains("mantenimiento"));}
    @Test public void staleRangeUses24HoursAndRejectsFutureTime(){DriverConfig c=c();long now=200000000;c.energyMode="PHEV";assertTrue(c.rangeStale(now));c.rangeUpdatedAtMs=now-86400000;assertFalse(c.rangeStale(now));assertTrue(c.rangeStale(now+1));c.rangeUpdatedAtMs=now+1;assertTrue(c.rangeStale(now));c.energyMode="GASOLINA";assertFalse(c.rangeStale(now));}
    @Test public void disabledZonesDoNotBecomeAnAppliedRestriction(){DriverConfig c=c();ZoneRule r=new ZoneRule();r.neighborhood="Zapopan";r.municipality="Zapopan";r.action=ZoneRule.Action.EVITAR;r.reviewedOn=LocalDate.now().toString();ScoreEngine.Evaluation a=ScoreEngine.evaluate(new OfferParser.Offer(100000,1,1,10,5,null,"Zapopan, Zapopan","Zapopan, Zapopan"),c,List.of(r),LocalDate.now(),12);assertTrue(a.zones.blocked);assertFalse(a.zoneBlocked);assertEquals(ScoreEngine.Color.VERDE,a.color);}
    @Test public void invalidReturnAndRatioSettingsAreRejected(){DriverConfig c=c();c.pickupShareAlertPercent=101;assertNotNull(c.validate());c.pickupShareAlertPercent=60;c.returnScenarioEnabled=true;c.returnScenarioKm=c.returnScenarioMin=0;assertNotNull(c.validate());c.returnScenarioKm=1;assertNull(c.validate());}
}
